# Workflow 의 이름
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정
# main 이라는 브랜치에 push 될 때 아래 Workflow 를 실행한다.
on:
  push:
    branches:
      - main

# 하나의 Workflow 는 1개 이상의 Job 으로 구성된다.
# 여러 Job 은 기본적으로 병렬적으로 수행된다.
jobs:
  # Job 을 식별하기 위한 id
  My-Deploy-Job:
    # Job 을 실행하는 Runner 를 설정
    # 나는 ubuntu 가장 최신 버전을 택하겠다.
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job 은 여러 Step 들로 구성되어있다.
    steps:
      - name: Hello World 찍기
        run: echo "Hello World" # 리눅스 코드

      - name: 여러 명령어 문장 작성하기
        run : |
          echo "Good"
          echo "Morning"
